AWSTemplateFormatVersion: "2010-09-09"
Description: Creates two Subnets, a DBSubnetGroup, an EC2 instance and a RDS instance.
Parameters:
    KeyName:
        Description: "Name of an existing EC2 KeyPair to enable SSH access to the instance"
        Type: "AWS::EC2::KeyPair::KeyName"
        ConstraintDescription: "mhs-ec2-instance"
Resources:
    EC2Instance:
        Type: "AWS::EC2::Instance"
        Properties:
            ImageId: "ami-077a5b1762a2dde35"
            InstanceType: "t2.micro"
            SecurityGroups: "sg-07bf27ca4b30fdee0"
            KeyName: !Ref KeyName
            VpcId: "vpc-035bd206feb45b6ef"
            SubnetId: "subnet-0e619498e81bb0871"
            AssociatePublicIpAddress: "true"
            Tags:
                -
                    Key: "purpose"
                    Value: "CloudFormationTesting"
            # UserData: 
            # #!/bin/bash
            # rm -rf /var/lib/cloud/*
            # sudo apt-get update
            # sudo apt-get install git
            # git clone https://github.com/mahesadhanaa/shell-script.git
            # cd shell-script
            # sudo chmod +x install-apache2.sh
            # sudo ./install-apache2.sh
Outputs:
    FirstEC2InstanceId:
        Description: "Instance Id of first EC2 Instance"
        Value: !Ref EC2Instance